controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
authentication_token:
    path: /api/authentication_token
api_auth_verify_otp:
    path: /api/auth/verify-otp
    methods: ['POST']